### ISSUE TITLE
Confusion about z_{e} and z_{e}^{'}

### ISSUE THREAD

**Issue by shaojiawei07** [AlbertOh90/Soft-VQ-VAE#1]
Hi, thanks for your great work!

I am interested in your work, but I feel confused about the notation z_{e}, z_{e}^{'}, and how to add noise \epsilon to the z_{e}?
![image](https://user-images.githubusercontent.com/57165574/83961541-c75d6880-a8c6-11ea-99fa-4f858b0cdf96.png)

From what I learn in the [code](https://github.com/AlbertOh90/Soft-VQ-VAE/blob/master/MINIST_clustering.ipynb) that the class **softVectorQuantizer** uses the output of the encoder as z_{e}^{'}.
 (The DNN adds the noise \epsilon to unobservable z_{e} implicitly, is it right?)

![image](https://user-images.githubusercontent.com/57165574/83961712-60d94a00-a8c8-11ea-8d86-a1fe42ed7e56.png)

Finally, is there a notation inconsistent in the following figure from [paper](https://arxiv.org/pdf/1905.11062.pdf), because the encoder can not directly output the unobserved z_{e}.

![image](https://user-images.githubusercontent.com/57165574/83961643-b6f9bd80-a8c7-11ea-808b-6566e74d3d7a.png)

**Comment by AlbertOh90** [comment]
Thank you for your interest. 
You could uncomment the line  "#inputs['z_mean'] = add_noise(inputs['z_mean'], 0.01)" in the MINIST_clustering.ipynb file to obtain noisy latent codes.  Although the noisy latent codes can improve the clustering performance in general,  the variance of the noise is a hyperparameter that depends on the specific model structures (MLP, CNN, etc..) and training data. Hence it needs to be chosen through validation. So maybe it is a good idea to just try out the noiseless version. The noiseless version will already perform better than the vanilla VAE in terms of clustering in our test. In this case, you could think of DNN is a "noisy approximator" that outputs z_e' which is a noisy version of z_e. And the figure should plot z_e' as you pointed out. In the paper, I want to express that encoder output z_e is unobserved by the decoder, and only z_e' (explicitly added noise) can be observed by the decoder. So the figure plots z_e. 
I hope I understand your question correctly. If you have further questions, please let me know (hanwei@kth.se).

**Comment by AlbertOh90** [comment]
Thanks for your interests of the paper.

**Comment by shaojiawei07** [comment]
Thanks for your reply.

It is clear to me now.
